// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDXittPDfapFDNid5Q39ZRmdavFxnUH4s',
    appId: '1:305715448501:web:3b63f3bc35b158fbcf0cfc',
    messagingSenderId: '305715448501',
    projectId: 'using-bloc',
    authDomain: 'using-bloc.firebaseapp.com',
    storageBucket: 'using-bloc.appspot.com',
    measurementId: 'G-30R602FBMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG2mYUlL0Ll14tEezPNMjH9Ui6jzrWhTM',
    appId: '1:305715448501:android:de68610032299ab9cf0cfc',
    messagingSenderId: '305715448501',
    projectId: 'using-bloc',
    storageBucket: 'using-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpcS18BP0WDDlyfGtFVGpMlSU71WoocPI',
    appId: '1:305715448501:ios:aee24260c7d40eb2cf0cfc',
    messagingSenderId: '305715448501',
    projectId: 'using-bloc',
    storageBucket: 'using-bloc.appspot.com',
    iosClientId: '305715448501-q5hf68b82lu62qj8imu3urivmqcmpklg.apps.googleusercontent.com',
    iosBundleId: 'com.example.usingFirebase',
  );
}
